### ISSUE TITLE
No sound in WPF Demo

### ISSUE THREAD

**Issue by gviddy** [Tyrrrz/YoutubeExplode#14]
Hey there,
I am running your WPF demo and it is downloading ok except that there is no sound....

This is an example URL, but i get no sound on all video i download... 1080p, mp4....
https://www.youtube.com/watch?v=J9vFS1MB4VY

**Comment by gviddy** [comment]
oh it's because I am downloading the video only.. I need to download the mixed version....

Therefore how can I get a 1080p video with audio attached ? They never seem to have a mixed 1080p version...

**Comment by Tyrrrz** [comment]
[Relevant wiki post](https://github.com/Tyrrrz/YoutubeExplode/wiki/FAQ#q-whats-the-difference-between-different-adaptive-modes). Also check out [this usage example](https://github.com/Tyrrrz/YoutubeExplode/wiki/Usage-examples#download-media-stream) which shows how to identify streams that have both audio and video.

Short answer: as you correctly noticed, some streams can have either only audio or only video. Mixed streams don't go above 720p in video quality. This approach allows Youtube to save a lot of storage space by playing 2 separate streams (video and audio) simultaneously instead of mixing them into one big stream.

Once you download 2 media streams (one for video and one for audio), you can combine them using a tool such as [ffmpeg](https://superuser.com/questions/277642/how-to-merge-audio-and-video-file-in-ffmpeg). To my knowledge, there are no .NET libraries that offer similar functionality, so everyone just ends up using ffmpeg via command line interface.

Hope that answered your question.

**Comment by gviddy** [comment]
yes... awesome... thanks for the info! 👍
