### ISSUE TITLE
Support 1080p or higher with sound?

### ISSUE THREAD

**Issue by omansak** [Tyrrrz/YoutubeExplode#150]
Can it download 1080p with sound?

**Comment by SlowLogicBoy** [comment]
No, it can not, you have to join audio stream with video stream, you have to do that using external tools like ffmpeg.
Here are few example:
This joins audio and video streams in memory and returns joined stream:
https://gist.github.com/SlowLogicBoy/63037d655cf8c667ae09ccebcf1164aa
you can use another stream instead of `FileStream`.
This downloads audio and video streams into a temp files and then joins them together:
https://gist.github.com/SlowLogicBoy/c6e76e1c4d85cddfe414dd436f5a82d8

**Comment by SlowLogicBoy** [comment]
Well, I can't help you with that.
What I do is I created Web Api, and my apps call it instead of referencing this library and doing stuff on client side, I do It on a server side.

Example of such api:
https://github.com/SlowLogicBoy/YoutubeExplode.AspNetCore.Mvc
Instead of returning yt explode stream you could return stream from my first example.

And then make UWP app call that api, in this case `localhost:5000/Youtube/DownloadVideo/{SomeId}`

**Comment by Tyrrrz** [comment]
Do consider my suggestion when it comes to playing.
As for downloading, I'm not sure what would be the solution for UWP. Perhaps you can host your own webserver that would mux and convert videos and then send them back to you. Something like what @SlowLogicBoy did.

**Comment by omansak** [comment]
@Tyrrrz FormatCode 140 (just audio .aac) download speed is so low in UWP why ?

**Comment by Tyrrrz** [comment]
Are you using the latest version?

**Comment by omansak** [comment]
@Tyrrrz Hey , I am using different download method ([DownloadOperation](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.downloadoperation)) , youtube have limited bandwidth for some resolutions . 
It downloading full speed less than 480p with 
```
       SetRequestHeader("range", "bytes=0-");
       SetRequestHeader("accept", "bits"); 
```
but this solutions no longe work gretear than 480p video ?
Do you know any solutions?

**Comment by Tyrrrz** [comment]
@omansak check out `GetMediaStreamAsync` here: https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/YoutubeClient.MediaStream.cs
Basically it splits the stream into segments and opens a new connection for each segment.
