### ISSUE TITLE
New Update?

### ISSUE THREAD

**Issue by darkdoctor** [Tyrrrz/YoutubeExplode#191]
Hi tyrrz.

Today I realized that to get media streams is much faster than before, like a few of seconds.

Have you improved it or ...?

**Comment by SlowLogicBoy** [comment]
Parsing logic was refactored to use new youtube json response. Changes can be seen here #187

**Comment by Tyrrrz** [comment]
Instead of creating an issue like that, you could've read the [changelog](https://github.com/Tyrrrz/YoutubeExplode/blob/master/Changelog.md).
And yes, like @SlowLogicBoy said, `GetVideoMediaStreamInfosAsync` is now, on average, twice as fast than it used to be.

Please, if you have questions like this one, I suggest asking them in the [gitter](https://gitter.im/YoutubeExplode/Lobby) chatroom instead of here.
