### ISSUE TITLE
Interface encapsulation for TryParseVideoId

### ISSUE THREAD

**Issue by mysteryx93** [Tyrrrz/YoutubeExplode#207]
As I'm refactoring my application based on Dependency Injection best practices to be able to run each class in a sandbox to run unit tests, I was pleasantly surprised to see YoutubeClient is based on an abstraction interface.

However, there is just one method that is missing from the abstraction interface, TryParseVideoId, since it is a static method instead of an instance method. It wouldn't be pretty for me to create a tiny dependency service just to provide this 1 small method.

Could you add this method to the interface? It can of course be available both on the class instance and as a static method.

**Comment by Tyrrrz** [comment]
Hi,
What is the use case where you want to mock TryParseVideoId?

**Comment by Tyrrrz** [comment]
Ah, right, dependency injection

**Comment by Tyrrrz** [comment]
Normally, if you want to make a purist dependency injection architecture, you would inject only your own interfaces/classes, not the ones coming from other libraries.

**Comment by Tyrrrz** [comment]
Although I can see that IYoutubeClient not covering parsing methods can be annoying when mocking too...

**Comment by mysteryx93** [comment]
I see no need to create a wrapper around your classes if they already have the right abstraction layer around them.

**Comment by SlowLogicBoy** [comment]
Since `TryParseVideoId` method does not depend on instance object (IYoutubeClient), it's more like a `string` extension, not some kind of operation that `IYoutubeClient` should do (I guess), It makes sense that it's static, and not part of `IYoutubeClient`, the only problem I see here that these static methods are part of `YoutubeClient` not some kind of parser.
IMO the best solution is to possibly create `YoutubeIdParser` that could be instanced and have static method, where Instanced methods would just redirect to static ones?

**Personal ramble.. you can ignore this:**
2nd thing is do you go to every library that exposes static methods instead of instanced method and ask them to make interface for them?
Now let's say you need to mock `File.WriteAllText()`? will you go to Microsoft to tell them to make it instanced and with some kind of interface?
Where I work we deal with this problem a lot and we have to ether use existing wrappers like this:
[SystemWrappers](https://github.com/jozefizso/SystemWrapper) that wraps, System static and non static classes to expose interfaces.
Or more commonly create our own, because we need to Mock those objects/static methods, because it interferes with our TDD.

**Comment by Tyrrrz** [comment]
Since this issue was opened I have thought many times on different aspects of dependency injection and the cargo cult surrounding it in .NET. My conclusion now is that libraries shouldn't provide interfaces for consumers because the abstractions need to be owned by the consumers and not the implementations (disregarding polymorphic scenarios which are not relevant to this library).

The future major release of YTE (when that happens) will drop `IYoutubeClient` altogether and if you plan to build a service layer around it, you will have to make your own abstraction that makes sense for your domain.
