### ISSUE TITLE
GetVideoMediaStreamInfos returns no streams

### ISSUE THREAD

**Issue by wesbyte** [Tyrrrz/YoutubeExplode#229]
Hello ~ I am using your excellent code for several months, it was working perfectly a few hours ago and now it can't parse any YouTube videos, please advise ASAP.

**Comment by yetiks** [comment]
Same here

**Comment by Tyrrrz** [comment]
I just looked into it, seems like YouTube removed stream infos from player response data. It might mean we need to go back to signature deciphering days...

**Comment by wesbyte** [comment]
Thanks for coming back to us that quick!
Could you take a look at https://safeshare.tv, it seems to work there!
When would you be able to solve this?
For me, all what I need is an updated version of YoutubeExplode.dll

Thanks again!

**Comment by wesbyte** [comment]
This URL is generated by safeShare.tv, it works fine, hope it helps you to detect what is wrong:

https://redirector.googlevideo.com/videoplayback?expire=1555595147&itag=18&dur=195.953&mime=video/mp4&ipbits=0&requiressl=yes&clen=9249430&lmt=1517368228384902&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,expire&c=WEB&initcwndbps=4193750&key=yt6&fvip=3&ms=au,rdu&id=o-AI7WCyLAISHvolZ6gl2vz5KeaePNetsdhPRPdKFCS-Rj&ei=Kyu4XPDBH-nmhwaf45mgDQ&mv=m&pl=22&mt=1555573474&mn=sn-vgqsenls,sn-vgqs7ns7&source=youtube&mm=31,29&ratebypass=yes&gir=yes&ip=34.206.4.28&signature=560CBF1DDD85D2E97C4CF1BD01D8FF6CDD98BFB4.9FA14B1C3578DC7E8EFE091BB7F617B9BBE1590B&fexp=23736685,23744176,23745074,23751767,23752869,23755886,23755898,23762649,23785333,23788835,23798632,23798737,23802148,23802652,23804294,23806466,23806734,9449243,9471235

**Comment by Tyrrrz** [comment]
Thanks. I believe I know how to fix it, it's just that it will involve some effort.

**Comment by yetiks** [comment]
Thats' great bro! I can't wait :)

**Comment by yetiks** [comment]
Let's buy him a coffe, guys!
https://buymeacoffee.com/tyrrrz

**Comment by wesbyte** [comment]
We appreciate your efforts so much! I hope you could be able to solve it ASAP, my website is down because of this and getting lots of complaints.
All I need is an updated version of the YoutubeExplode.dll

**Comment by wesbyte** [comment]
@yetiks @Tyrrrz I have just taken your advice and bought him coffee, I hope this encourages him to do it ASAP. Thanks.

https://buymeacoffee.com/tyrrrz

**Comment by yetiks** [comment]
@wesbyte me too and i am sure it will :)

**Comment by wesbyte** [comment]
@Tyrrrz do you mean you can't solve this and there is no way to make it work?

**Comment by hung1xpro** [comment]
> @Tyrrrz do you mean you can't solve this and there is no way to make it work?

It mean another thread same like u so he link 2 threads to work.

**Comment by wesbyte** [comment]
@hung1xpro thanks bro for elaborating this. Appreciated!

**Comment by Tyrrrz** [comment]
I'm currently working on a fix, it's not trivial. As a workaround you can try using version 4.5.3, it works for some videos, which is probably better than nothing.

**Comment by Montegro** [comment]
Looking forward to the fix!

**Comment by Tyrrrz** [comment]
@wesbyte if you are in an absolute hurry, you can use artifacts from [the latest feature branch build](https://github.com/Tyrrrz/YoutubeExplode/files/3095487/YoutubeExplode.4.6.8.zip). It still fails some tests and not production ready but it will work on 90% of videos. You can just replace the binaries for now. When this issue is fully resolved, I will release a proper new version. Full fix will take some time.

**Comment by wesbyte** [comment]
Thanks for this @Tyrrrz, I hope you release a NuGet package soon.

**Comment by Montegro** [comment]
Is there a way to NuGet the Feature Branch from Visual Studio?

**Comment by Tyrrrz** [comment]
If you clone the repository, just build YoutubeExplode project, the .nupkg will appear in YoutubeExplode/bin/Debug (or bin/Release, depending on configuration).

**Comment by SnakyBeaky** [comment]
Having the same issue. Yesterday worked fine. There doesn't seem to be any official announcements from YouTube in their devblog/changelog.

**Comment by Tyrrrz** [comment]
I doubt they would announce this since it's not public API

**Comment by luca233** [comment]
> Thanks for this @Tyrrrz, I hope you release a NuGet package soon.

I use that Branch and all is fine  with videos last played

**Comment by nizata** [comment]
Looking forward to the fix

**Comment by yetiks** [comment]
Hey - i am using branch now and seems to works in most movies now. I found that movie id:SkRSXFQerZs returns: Error reading JToken from JsonReader. Path ", line 0, position 0.

**Comment by DarkEyeDragon** [comment]
Just out of curiosity, will any of this impact performance, download speeds?

**Comment by WhiteLionATX** [comment]
Is this bug fixed ? On Nuget last update is 30 of March...

**Comment by TaoziDB** [comment]
Is it possible to push out a Nuget update, mark it beta version, partially working is better than not working at all, thanks a lot.

**Comment by Tyrrrz** [comment]
Sorry, didn't have internet access the past few days.

@DarkEyeDragon the initial request will be slower, the actual download speed will not be affected. That said, the overall speed will not degrade lower than youtube-dl or other library, because YoutubeExplode was the only library that used a faster (now non-working) way of getting streams.

@TaoziDB I will push a new prerelease when I get home in a couple of hours

**Comment by Tyrrrz** [comment]
https://www.nuget.org/packages/YoutubeExplode/4.7.0-alpha - pre-release

**Comment by Hanzalah-Adalan** [comment]
owhhh yeahhh! 😍

**Comment by TaoziDB** [comment]
Thanks for quick response, videos are working fine now, but stream playing is broken, stream playing was fine for 4.6.8

**Comment by Tyrrrz** [comment]
@TaoziDB what do you mean by stream playing?

**Comment by TaoziDB** [comment]
live stream playing, streamInfoSet.HlsLiveStreamUrl is null now

**Comment by Tyrrrz** [comment]
I see, ok. I will look into it.

**Comment by darkdoctor** [comment]
Is this bug fixed or still working on it dear Tyrrrz ? :)

**Comment by anionDev** [comment]
`4.7.0-alpha` seems to work. Thank you very much.

**Comment by Tyrrrz** [comment]
@darkdoctor try the prerelease version above for now

**Comment by yetiks** [comment]
@Tyrrrz 4.7.0-alpha seems to work almost great. I've found a couple of movies that returns some streams which not work and have size 0kb.
Check those videos ID please:
azRdr71z0fc
zYpsxF1PysI
VSaeqvdEglc
3bMOAjUA84Q
u-AITYlZMc0
CAuiKv7Dn_w
UjYZGsYYopQ
RtTsQ2KrnyE
ODRgqYKt01k - no stream
4dl8nu74F5w
vynYEDR9OCs
_NAV6CUeN60
BcFZuF-rfMI
l8UL23m1qQY
OovWYSCQHXk
dUu2IzNwRa0
UrddRYq4QrA
RNHrZNmPfPU
rnLqs-MQeLI
V_NJghOkhkc
OzpopPmfIZU
klujYKlu4w8
MW9pWofQXgE

**Comment by UnboundGodz** [comment]
Hmm, for some reason even after updating through Package Manager through VS2017/VS2019 the project still gives me error "System.NullReferenceException: 'Object reference not set to an instance of an object" for some reason. lol man I need to get back into using VS.

**Comment by bkmaster19** [comment]
@Tyrrrz Hey Alexey, I read your article "Reverse-engineering-YouTube" on your website and build with these informations my own YT downloader app with JS for education purpose. Unfortunately since YT did remove the stream infos from "player_response" it doesn't work. As I read in this post, you already find a workaround. 

Could you please describe how your workaround is (not your code) - I mean what is the new way to get to the stream infos with the itag? It should be like a hint for me (or maybe for others), after that, I can just continue by my own to fix my app (which takes a lot of time, because im new in that stuff, but this is no issue). Thank you.

**Comment by Tyrrrz** [comment]
@UnboundGodz did you update to 4.7.0-alpha?
@bkmaster19 after YT removed streaming data from `player_response`, I just reverted to the old way of resolving streams, which is actually described in the article. Player resposne based resolving wasn't described in the article.

**Comment by UnboundGodz** [comment]
> @UnboundGodz did you update to 4.7.0-alpha?
I did through VS Nuget, and relaunched VS to confirm any changes but this is my first time using it so I could be going about it wrong.

**Comment by bkmaster19** [comment]
@Tyrrrz Thank you for your quick response. Just to be sure that I understand you correctly: 

Do you mean with 'the old way of resolving streams' like you described in the summary (steps 1-12) of this article or is there a specific chapter of this article? Thank you.

**Comment by Tyrrrz** [comment]
@UnboundGodz does it happen on all videos?
@bkmaster19 yes, the summary (and the entire article) is still valid

**Comment by UnboundGodz** [comment]
@Tyrrrz Yea it appears for videos from 2015-2019 any random video it comes back with:

> System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DemoConsole
  StackTrace:
   at DemoConsole.Program.<MainAsync>d__1.MoveNext() in C:\Users\Brandon\Documents\Visual Studio 2019\YoutubeExplode-master\DemoConsole\Program.cs:line 39
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DemoConsole.Program.Main(String[] args) in C:\Users\Brandon\Documents\Visual Studio 2019\YoutubeExplode-master\DemoConsole\Program.cs:line 60

**Comment by Tyrrrz** [comment]
So after working on this for quite a lot of time, I decided to give an update because I've managed to make some progress.

As everyone already knows, YouTube made some changes that broke YoutubeExplode. Some of you already know that these changes have something to do with stream infos no longer being inside `player_response`, but this is only part of the problem (albeit the biggest one). As it appears, they've also added a new way of passing signatures in the URL, but only for some videos, some of the time. Minor things like `PreviewVideoId` for purchasable videos was also broken. Different info that we used in the past is no longer directly available.

To top things off, YouTube is a bit random when it comes to its behavior, it may respond with different data every now and then, and also when requested from different environments (I've noticed a lot of discrepancies between running tests locally and on appveyor, possible due to different IPs and locales).

My main problem was (and still is) to handle all the hundred different logic branches while ensuring code is still sane and legible. Recent YouTube changes has forced me to take a few large steps back in that regard, bringing back signature deciphering code, itag-based and some other heuristics, weird fallback and retry approaches, etc. I can say that I succeeded to some extent but the code is still awful and in some parts illegible and I don't think I can make it much better that easily.

So far I've been able to make YoutubeExplode work for vast majority of videos and fixed quite a lot of issues that were present in 4.7.0-alpha. The [tests are finally all green](https://ci.appveyor.com/project/Tyrrrz/youtubeexplode/builds/24096569/tests), but unfortunately this is not a guarantee that it will work for all videos. [**I have pushed a new nuget package - 4.7.0-beta, please try it out.**](https://www.nuget.org/packages/YoutubeExplode/4.7.0-beta)

Tomorrow I'm going on vacation to Prague and Wroclaw for a bit over a week, so I won't be able to actively work on YoutubeExplode so hopefully I will have a lot of feedback on 4.7.0-beta by then. :)

@TaoziDB live streams should work now, but I haven't tested. Please test them.

@yetiks I have looked at some videos, it seems they have at least 1 stream. If you go to their watch page on YouTube, they usually have only a few, low qualities available. Maybe YouTube is purging some streams?

@bkmaster19 to correct my prior statement, the approach explained in the article still works, but only for 95% of videos, about 80% of the time. :)

@UnboundGodz it could be that the videos you're testing don't have muxed streams or something. It seems you're experiencing the same issue as @yetiks.

**Comment by XFox111** [comment]
@Tyrrrz, Hi. Unfortunately, not live steams work. I've checked 5 streams and 4 of them doesn't work. 3 of them has not empty audio/video arrays (but files themselves shows nothing) but null stream url. For example DPfHHls50-w
Last one has crashed on calling 'YoutubeClient.GetVideoMediaStreamInfosAsync(string videoId))' with "System.ArgumentException: 'Unknown encoding [unknown]. Parameter name: str'" exception (eg. 4993sBLAzGA)
Hope you will fix it after vacation)

**Comment by Gart79** [comment]
@Tyrrrz thanks a lot for this great job!!!  The 4.7.0-beta, is working perfect for me for downloading videos.

**Comment by TaoziDB** [comment]
@Tyrrrz live stream playing doesn't work. 

Thanks for the quick effort and have a nice vacation.

**Comment by UnboundGodz** [comment]
@Tyrrrz Thank you for all your work, and your quick responses. Yea its abit weird they will provide video-only or audio-only, then ill have to merge them lol. Its not the end of the world, since your program is like the only one that actually will give the user the best downloadable quality video. So thank you. Hopefully down the line, it does work more efficient, fingers crossed! :)

**Comment by yetiks** [comment]
Thanks @Tyrrrz - take a look this video: VSaeqvdEglc or this 3bMOAjUA84Q. If you watch video there are more resolutions that YouTubeExplode returns. Have a nice holiday!

**Comment by sudipmandal** [comment]
@Tyrrrz Thanks for the great work and taking the time to explain! Enjoy your vacation and hope you are able to fix the streaming issue once you are back.

**Comment by brad2575** [comment]
Want to add I love this and it has been very helpful.  Just for personal use wrote app to look at file with youtube links, loop through all links, download movies, extract/convert to .mp3, and save, then remove the movie file.

The beta release worked on about 50 I just ran in my program.  So THANKS!

**Comment by Tyrrrz** [comment]
Hi guys, thanks for the kind words! I'm back, will look into outstanding issues now. :)

**Comment by Tyrrrz** [comment]
PS: Prague & Wroclaw were amazing. 😍 [Here are a few pictures](https://www.instagram.com/tyrrrz) if you're into that.

**Comment by Tyrrrz** [comment]
I pushed `4.7.0-beta2` version, it should help with live streaming issues some of you were having: https://www.nuget.org/packages/YoutubeExplode/4.7.0-beta2.

@yetiks I looked into it, seems like the other streams are DASH streams that are partitioned. We are currently skipping those streams. Do you remember if older YoutubeExplode was able to see the other streams before the YouTube changes that broke everything?

**Comment by TaoziDB** [comment]
@Tyrrrz live streaming works now, thanks.

**Comment by Tyrrrz** [comment]
Merged the fix to master, it seems pretty stable now.

As others pointed out, some videos have fewer media streams than before, in particularly muxed streams. I think it could mean that YouTube is finally getting rid of muxed streams.
In some other cases, certain adaptive streams that YouTube is able to play are missing in YoutubeExplode, but that's because they're now only available as segmented streams in DASH manifest (#159 is the related issue).

**Comment by ghootifarangi** [comment]
Hi dear Tyrrrz
This link not work.
Please check it.
https://www.youtube.com/watch?v=e24QwZh9fCw

**Comment by Tyrrrz** [comment]
@ghootifarangi seems like the same as #237 #219 ?

**Comment by ghootifarangi** [comment]
yesssss :( There is no solution?

**Comment by Tyrrrz** [comment]
Unfortunately no, besides not using muxed streams. The problem seems to be YouTube-side.
