### ISSUE TITLE
Remove Fody usage, write ConfigureAwait manually

### ISSUE THREAD

**Issue by Tirraon** [Tyrrrz/YoutubeExplode#242]
Seems like there are several issues with it.
Current version in YoutubeExplode doesn't support net45: https://github.com/Fody/ConfigureAwait/issues/56
Latest version support only netstandard20: https://github.com/Fody/ConfigureAwait/issues/32

And in actual branch Fody is ignored for netstandard11, so we can say, that Fody works only for netstandard20 in YoutubeExplode.

**Comment by Tyrrrz** [comment]
Hi.

Actually the first issue was opened by me and I managed to get it to work. You're right though that netstandard1.1 doesn't get weaved.

There are few things in C# that I hate, `.ConfigureAwait(false)` is unfortunately one of them. This project alone had seen 4 PRs related just to that.

I agree that Fody is a volatile underwater mine and I would ultimately have some tool that rewrites code instead of assemblies.
