### ISSUE TITLE
Add few more playlist types

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/YoutubeExplode#25]
UU{channelId} - Channel Uploads
PU{channelId} - Popular

When I use these, exception is throw "Unexpected playlist ID [{0}]".

After modifying it through reflection by instead of [throwing, returning PlaylistType.UserMode](https://github.com/Tyrrrz/YoutubeExplode/blob/master/YoutubeExplode/Models/PlaylistInfo.cs#L89), these playlists yield results, so I think these should be added too.
You can differentiate them by 
"UU" - Channel Uploads, 
"PU" - Popular channel uploads, 

Maybe a good Idea would be to return PlaylistType.Unknown when you can't differentiate what type it is.

This is also an opportunity to add method GetChannelUploadsAsync(string channelId);

However, if I look up youtube channel url it is "https://www.youtube.com/channel/UC*" so for uploads I have to make it to "UU*" same with "PU*"

**Comment by Tyrrrz** [comment]
Hey
Thanks for finding this.

I will add these ASAP.

It actually used to return `PlaylistType.Unknown` and most of enums had an `Unknown` value. I moved away from that because I preferred to not handle situations where at least part of the information could not be parsed because there was no guarantee anymore that the rest of it was parsed correctly either. I'd rather have it work predictably on something it was intended and tested to work with and throw on the slightest sign of doubt.

> This is also an opportunity to add method GetChannelUploadsAsync(string channelId);

Does it return all the videos or is it almost hard capped?

**Comment by Tyrrrz** [comment]
Also, what's the difference between UU and UL?

**Comment by SlowLogicBoy** [comment]
I would say it's capped, but with medium channels I'm able to get more than 100 videos, so I would assume that if it's capped the cap would be 200 or more .

**Comment by Tyrrrz** [comment]
Can you test it on a channel that has over 200 videos, just to make sure? If it correctly scraps everything then I'll probably just replace the current implementation with this one.

Also it looks like the new playlist types were introduced as part of the new Youtube design/layout. I've never seen them prior to that.

**Comment by SlowLogicBoy** [comment]
Holy ... with one huge channel I got 1483 videos, so I think it's not capped.. at least for now.

**Comment by Tyrrrz** [comment]
Awesome. I guess I can safely replace the old API then.
