### ISSUE TITLE
Add channelID in the video format

### ISSUE THREAD

**Issue by AnonymusRaccoon** [Tyrrrz/YoutubeExplode#260]
Since you are starting to support more than videos with channels and playlists, it may be better for the users to have a channelID returned from the GetVideoAsync and others methods that use the YoutubeExplode.Models.Video model.

I think that it's possible since all html pages of youtube allow the user to directly go to the channel with a link so you might only need to parse it.

Thanks for reading, great library btw!

**Comment by PoLaKoSz** [comment]
I would like to make a PR to implement this, because my app extensively uses searching and i have to know the Channel ID in order to bind to a Channel (in a DB) which means if i have 10 search results i call YouTube **at least 20 times**.

So far i am in a process to implement this in the `YoutubeClient.Channels.GetUploadsAsync()` method but the endpoint only exposes the Channel ID and its name, there is no logo URL. What should i do? Set the logo URL to null, and use the already implemented Channels.Channel class or implement a new one which has only 2 properties?

**Comment by Tyrrrz** [comment]
You can just add `ChannelId` as a separate property to `Video`. But note that all methods that return `Video` should populate it.

**Comment by PoLaKoSz** [comment]
All right thank You for the answer. What could be a good property name for the `ChannelId` type? ChannelId? AuthorId?
Note for myself : There is a `Video.Author` property which is the actual name of the `Channel`.

**Comment by Tyrrrz** [comment]
`public ChannelId ChannelId { get; }` is fine.

**Comment by PoLaKoSz** [comment]
Got it, thanks.
