### ISSUE TITLE
429 - Any heavy users here?

### ISSUE THREAD

**Issue by blackjack4494** [Tyrrrz/YoutubeExplode#436]
I am not using this tool nor do I download from youtube.  
Just wondering if since the introduction of Segmented Streams there have been less or no problems at all.  

It is understandable that google implements some ways to slow down automatic scraping on youtube.

Cheers :)

**Comment by Tyrrrz** [comment]
Segmented streams change was unrelated and didn't impact this in any way. If you send too many requests or use a shared IP, you will still get 409s. I don't get them with my own workload though.

**Comment by farazp** [comment]
I got this after two requests!

how can handle that? have you any solutions? 

Failed to perform an HTTP request to YouTube because of rate limiting.
This error indicates that YouTube thinks there were too many requests made from this IP and considers it suspicious.
To resolve this error, please wait some time and try again -or- try injecting an HttpClient that has cookies for an authenticated user.
Unfortunately, there's nothing the library can do to work around this error.

Method: GET, RequestUri: 'https://www.google.com/sorry/index?continue=https://youtube.com/watch%3Fv%3DiHdviZkM7S4%26bpctr%3D9999999999%26hl%3Den&hl=en&q=EgQFxNa3GP2Dz_oFIhkA8aeDS7Y9wpR-nE_JqGudIj5hfzWUpjRmMgFy', Version: 2.0, Content: <null>, Headers:
{
  User-Agent: Mozilla/5.0
  User-Agent: (Windows NT 10.0; Win64; x64)
  User-Agent: AppleWebKit/537.36
  User-Agent: (KHTML, like Gecko)
  User-Agent: Chrome/80.0.3987.163
  User-Agent: Safari/537.36
  Accept-Encoding: gzip
  Accept-Encoding: deflate
}

StatusCode: 429, ReasonPhrase: '', Version: 2.0, Content: System.Net.Http.StreamContent, Headers:
{
  Server: HTTP
  Server: server
  Server: (unknown)
  Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
  Cache-Control: no-store, must-revalidate, no-cache
  Date: Sat, 05 Sep 2020 16:51:09 GMT
  Pragma: no-cache
  x-xss-protection: 0
  Content-Length: 2941
  Content-Type: text/html
  Expires: Fri, 01 Jan 1990 00:00:00 GMT
}

**Comment by Tyrrrz** [comment]
You can check the discussions in #376
