### ISSUE TITLE
Return a more specific error message when playlist is unavailable

### ISSUE THREAD

**Issue by derech1e** [Tyrrrz/YoutubeExplode#445]
Hey. The idea is to get a more detailed error message, of the fail reason from the download. For example, in the case of a private playlists, simply return a response that indicate that. 

Youtube already has this feature: 
![image](https://user-images.githubusercontent.com/39240736/93923201-588c0a00-fd13-11ea-8dbe-f245f774a0bd.png)

It would be very nice.
Thank you!

**Comment by bcwood** [comment]
I've been doing some testing on this, and you can't differentiate between a playlist that is private, and a playlist that doesn't exist. In both cases, the response returned is `400 : Bad Request`.

I could still improve the error message to say something along the lines of _"This playlist cannot be found. It either does not exist, or is private."_ Would that be acceptable?

**Comment by Tyrrrz** [comment]
Yeah, that message would be fine. The problem currently is that 400 is automatically handled by `YoutubeHttpClient` here:

https://github.com/Tyrrrz/YoutubeExplode/blob/530e9d678b586f892d198d667e4400cd3d495b85/YoutubeExplode/ReverseEngineering/YoutubeHttpClient.cs#L17-L34

You would either need to change `PlaylistResponse.GetAsync()` so that it passes `ensureSuccess = false` and checks everything itself or maybe rework this automatic error handling so it can work well in both scenarios.

**Comment by bcwood** [comment]
I was thinking the same thing. I think I'll probably go the route of passing `ensureSuccess = false`. I imagine that reworking that automatic error handling will have wide-reaching effects.
