### ISSUE TITLE
CancellationToken for DownloadMediaStreamAsync()

### ISSUE THREAD

**Issue by rqnn** [Tyrrrz/YoutubeExplode#47]
Hello!
I was wondering, if you had any solution to my following problem:
I included a CancellationToken into the DownloadMediaStreamAsync()-Method, and now I (obviously) get an exception thrown at me (the nasty MessageBox that tells me a Task was aborted), whenever i cancel a video download.
Is there any way to suppress that thing and maybe handle it with a custom MessageBox through some kind 
of event?
I've browsed most of the code, but couldn't come up with a sollution myself (except for messing with your code and compiling a modified library myself, which I'd rather not do, because I'm not that good at coding really, and also I don't know if your code is licensed or something?).

Regards, thanks in advance, and keep up the awesome work!

**Comment by Tyrrrz** [comment]
Hello. Thank you for your interest in the library.
Cancelled tasks do indeed throw an exception, because being cancelled puts them into an exceptional state. ;)
Normally what you would do is have a try/catch block as shown [here](https://blogs.msdn.microsoft.com/andrewarnottms/2014/03/19/recommended-patterns-for-cancellationtoken/) (scroll down to "Handling cancellation exceptions").

**Comment by rqnn** [comment]
Awesome, I didn't expect it to be so simple. :)
Now everything works totally fine.

Thank you a lot!

**Comment by Tyrrrz** [comment]
Glad I could help
