### ISSUE TITLE
Age-restricted videos are not working again

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#478]
Judging by the latest nightly CI runs:
https://github.com/Tyrrrz/YoutubeExplode/actions?query=workflow%3ACI

The story repeats itself:
#460 #441 #394 #287 #65

**Comment by derech1e** [comment]
Maybe it is useful to implement a Google (Youtube) Account link to bypass this problem, if someone want to download that videos.

**Comment by Tyrrrz** [comment]
Well you can always provide your own pre-authenticated `HttpClient` and that will work.

**Comment by CCRed95** [comment]
@Tyrrrz Do you happen to have / know of any example of configuring an HttpClient and authenticating with a youtube account to get passed the 18+ sign in age gate? 18+ age restricted videos are not working again because the youtube.com/embed/id workaround doesn't bypass age authentication now. I'm trying to figure out how to configure an auth HttpClient, and I can't figure it out. 

Thanks!!

**Comment by Tyrrrz** [comment]
@CCRed95 I haven't done it myself, but there were some discussions here:
#497
