### ISSUE TITLE
Improvement for PlaylistClient GetVideosAsync

### ISSUE THREAD

**Issue by raelb** [Tyrrrz/YoutubeExplode#498]
Nifty piece of code in `PlaylistClient GetVideosAsync`.

If I follow correctly, besides exiting at 

    if (countDelta <= 0)
      break;

there should also be another reason to break, i.e. if `response.GetVideos().count < 100`. With the current code, there is always a next http request, even though it is known that there are no more videos, e.g. for a small playlist. :)

**Comment by Tyrrrz** [comment]
It can return < 100 if the playlist contains deleted videos. It's possible that 1st page returns 98 videos, but 2nd page returns 100 videos.

**Comment by raelb** [comment]
oh i c. Do you have a sample playlist where that occurs?

**Comment by Tyrrrz** [comment]
I think one of these two may have it:

https://github.com/Tyrrrz/YoutubeExplode/blob/a7cbf48264af64ea5bd7a2f6aac891207a4ae965/YoutubeExplode.Tests/PlaylistSpecs.cs#L104-L105

Otherwise I would try to find any playlist with deleted videos. They are quite common, especially with music videos (which get deleted on copyright claims).

**Comment by raelb** [comment]
Thanks, I will look into it.
