### ISSUE TITLE
Age-restricted videos are no longer playable

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/YoutubeExplode#503]
Looks like this is the final nail in the coffin, as YouTube's embed no longer plays age-restricted videos anymore: https://www.youtube.com/embed/SkRSXFQerZs?bpctr=9999999999

Does anyone know of another workaround? If not, it seems that the only way to play them going forward will be to use a pre-authenticated `HttpClient`.

Edit: it seems that the videos are playable, but only sometimes, so retrying helps. However, it might be because YouTube hasn't fully rolled out the change yet.

**Comment by fartwhif** [comment]
`Select(s => Regex.Match(s, @"['""]PLAYER_CONFIG['""]\s*:\s*(\{.*\})").Groups[1].Value)`

the PLAYER_CONFIG is missing from the embedded player page source, even when using proper headers, so it must have been replaced with some other information and/or procedure because the embedded player does work in a "proper" browser.

**Comment by Tyrrrz** [comment]
What does "proper" browser mean?

**Comment by fartwhif** [comment]
sorry i meant a browser i use to test with that isn't modified
