### ISSUE TITLE
Metadata can't be resolved for mix playlists

### ISSUE THREAD

**Issue by markushl** [Tyrrrz/YoutubeExplode#555]
### Version

v6.0.2

### Details

When trying to get videos from a playlist I get a PlaylistUnavailableException in `public async ValueTask<PlaylistExtractor> GetPlaylistAsync(...)` [ YoutubeController.cs]
Examples:
https://www.youtube.com/watch?v=kKDO8Rxw3vs&list=RDkKDO8Rxw3vs&start_radio=1 -> Playlist 'RDkKDO8Rxw3vs' is not available.
https://www.youtube.com/watch?v=3U4lQ8xX3ag&list=RDEMPeuXuiddECzwmszjRj1EtQ  -> Playlist 'RDEMPeuXuiddECzwmszjRj1EtQ' is not available.

### Steps to reproduce

Insert one of the above mentioned URLs in Tyrrz/YoutubeDownloader.

**Comment by Tyrrrz** [comment]
This is because when you open the playlist directly (https://www.youtube.com/playlist?list=RDEMPeuXuiddECzwmszjRj1EtQ), it says that the playlist is unviewable. We rely on this page to extract playlist data.

![image](https://user-images.githubusercontent.com/1935960/120895840-a7dd4680-c5d3-11eb-94dd-83d19e8cc21e.png)

Looks like we need a workaround for mix playlists.
