### ISSUE TITLE
Compatibility under Windows XP

### ISSUE THREAD

**Issue by twse** [Tyrrrz/YoutubeExplode#56]
Compatibility under YoutubeExplode has not been tested under Windows XP and any attempt to run YoutubeExplode from Windows XP will display a critical error saying **YoutubeExplode.exe is not a valid Win32 application**.

**Comment by Tyrrrz** [comment]
I'm not sure how you're trying to "run" YoutubeExplode because it's a library. Either way, since it targets .NET 4.5+, it won't work on Windows XP. It's not easy to make it compatible with .NET 4.0, nor is it worth it because I have no plans of supporting legacy operating systems in any of my projects.
