### ISSUE TITLE
Missing 14393 support from newest nuget version 6.0.3

### ISSUE THREAD

**Issue by TaoziDB** [Tyrrrz/YoutubeExplode#568]
### Version

ver 6.0.3

### Details

last time I used this nuget is ver 4.7.9 for 14393, when I got back to this nuget recently to try ver 6.0.3, I found out that ver 6.0.3 no longer works for 14393, in fact, not works for 14393 since ver 5.0.0, I am wonder if it is possible to add 14393 support back to 6.0.3? Thanks

### Steps to reproduce

no support for 14393

**Comment by Tyrrrz** [comment]
What is 14393?

**Comment by TaoziDB** [comment]
Windows 10 build 14393, also known as the Anniversary Update or version 1607

**Comment by Tyrrrz** [comment]
There is nothing about the package itself that makes it specific to any Windows build.

**Comment by TaoziDB** [comment]
If you make a simple UWP app with target version of Windows 10 build 14393 and min version of Windows 10 build 14393,
here is the error when installing ver 6.0.3, 
package YoutubeExplode 6.0.3 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393)

The newest version supports 14393 is ver 4.7.16,

**Comment by Tyrrrz** [comment]
Please include this context in the issue next. It wasn't clear what the issue was about and having this information ahead of time could have saved us both some time.

Version 4.7.16 was the latest version to target .NET Standard 1.1, which I assume is the latest version of .NET Standard that uap10.0.14393 supports. There's some extra context here: #323.

In short, there's no plan to restore older targets, so you'd have to bump your UWP target version.
