### ISSUE TITLE
YoutubeExplode failed to fetch video

### ISSUE THREAD

**Issue by YT-Advanced** [Tyrrrz/YoutubeExplode#754]
### Version

v6.3.9

### Platform

.NET 7.0 Windows 11

### Steps to reproduce

Using your YoutubeExplode to fetch this video:
https://youtube.com/watch?v=Cr381pDsSsA

### Details

YoutubeExplode failed to fetch the above video because this video:
- Is age-restricted
- The video author disabled embeded view
You can check this PRs for fixing it:
https://github.com/yt-dlp/yt-dlp/pull/600

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project

**Comment by Tyrrrz** [comment]
> * You can check this PRs for fixing it:
>   [[youtube] Add age-unverified account age-gate bypass (EU) yt-dlp/yt-dlp#600](https://github.com/yt-dlp/yt-dlp/pull/600)

The approach used in that PR is only relevant to authenticated scenarios: https://github.com/yt-dlp/yt-dlp/blob/db8b4edc7d0bd27da462f6fe82ff6e13e3d68a04/yt_dlp/extractor/youtube.py#L3716-L3718

Age-restricted videos already work fine if you're authenticated, so no changes are required in that aspect.

For unauthenticated scenarios, it's not feasible to make age-restricted videos work consistently. Different workarounds appear, but they're temporary because this use case is not supported by YouTube itself.
