### ISSUE TITLE
Method DownloadMediaStreamAsync error with UWP .Net Core

### ISSUE THREAD

**Issue by awscodu** [Tyrrrz/YoutubeExplode#83]
Everything works great except whenever I type this code I'm given an error saying that the class YoutubeClient does not contain an definition "DownloadMediaStreamAsync". I tried earlier releases and found that the same thing happened and to more methods like "GetVideoAsync".

`await client.DownloadMediaStreamAsync(streamInfo, outputFilePath);`

I'm using the latest version of .Net Core.

**Comment by Tyrrrz** [comment]
What framework does your project target?

**Comment by awscodu** [comment]
Universal Windows Fall Creators Update (10.0; Build 16299)

**Comment by awscodu** [comment]
I just tested it on a .Net Core console app and its working fine. I have no idea why .Net Core UWP is targeting the .net standard version of the build instead, this is very strange.

**Comment by Tyrrrz** [comment]
Maybe it doesn't support the full feature set of .net core. In that case you can still use `GetMediaStreamAsync` and save the stream manually.

**Comment by Tyrrrz** [comment]
Also, I'm not sure what ".net core UWP" actually is because I was under the impression UWP is a separate platform, which can reference .net standard assemblies. Judging from [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), UWP v10 will target YoutubeExplode .net standard 1.1 version which doesn't have the `Download...` methods. Apparently, if you somehow upgrade it to v10.0.16299, it should use the .net standard 2.0 version.
