### ISSUE TITLE
Side effect on System.Text.Json: NullabilityInfoContext is not supported in the current application

### ISSUE THREAD

**Issue by Walter5923** [Tyrrrz/YoutubeExplode#849]
### Version

6.5.0

### Platform

.NET MAUI 8.0.100 / Android

### Steps to reproduce

- Install update 6.5.0. 
- Serialize some objects with System.Text.Json to a file or 
- Deserialize the data from a file

### Details

Hi Tyrrrz,

Thank you very much for your great library.

With the update to version 6.5.0 I’ve got an odd side effect in my project (MAUI 8.0.100, Android). I use `System.Text.Json` to serialize and deserialize some data to and from files. This data has got no reference to YoutubeExplode or any other library – it's just a class with some string and integer properties. When I update to version 6.5.0 this doesn’t work anymore, when I go back to 6.4.4 it works again.

Both when serializing or deserializing, I get an `InvalidOperationException` in `void EnsureIsSupported()`, `System.Private.CoreLib`:

> NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it.

The setting `<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>` does work. But should YoutubeExplode influence `System.Text.Json`?

Thank you very much for help.

### Checklist

- [X] I have looked through existing issues to make sure that this bug has not been reported before
- [X] I have provided a descriptive title for this issue
- [X] I have made sure that this bug is reproducible on the latest version of the package
- [X] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

**Comment by Tyrrrz** [comment]
Hi @Walter5923.

The issue here is that YoutubeExplode depends on S.T.J and in the latest version that dependency was bumped to match the version used in .NET 9. I assume that nullability context check didn't exist in previous versions of S.T.J? Not sure.

I always build my libraries by targeting the latest .NET version and then use compatibility packages and polyfills to make them available on older frameworks as well. In this case, when using YoutubeExplode from a .NET 9 application, it will not bring its own dependency of S.T.J at all and just use whichever version is provided by the framework. On older targets, however, it will use the NuGet package in order to make sure that in both instances, YoutubeExplode relies on identical API surfaces.

I'm not sure about MAUI specifically, but I imagine moving to MAUI .NET 9 would help resolve your issue without any additional project settings.

**Comment by Walter5923** [comment]
Hi Tyrrrz,

Thank you very much for your reply and your explanation. I guess, the default setting of `NullabilityInfoContextSupport` in .NET 8 MAUI is true and it got changed to false somehow through YoutubeExplode using the latest .NET version. Setting it back to true in the project file of my application works fine. Maybe this helps some other people to solve this problem… I hope, that I can upgrade my application to .NET 9 soon – at the moment the MAUI CommunityToolkit doesn’t support.NET 9 yet.

Thanks again.
