### ISSUE TITLE
DownloadMediaStreamAsync taking too long

### ISSUE THREAD

**Issue by Kriste00** [Tyrrrz/YoutubeExplode#85]
When using `DownloadMediaStreamAsync` to download even a short video it will use up to a minute to return.
PS: It worked fine a few days ago.

**Comment by Tyrrrz** [comment]
Looks like an issue with ratebypass

**Comment by Kriste00** [comment]
ratebypass?

**Comment by Tyrrrz** [comment]
Only concerns adaptive streams, youtube-dl is having the same issue

**Comment by Tyrrrz** [comment]
The issue is that Youtube normally serves media streams at the same that you play them so that 5 minute video will take around 5 minute to download. There is a parameter that lets you bypass this limitation, called `ratebypass`, which YoutubeExplode and other libraries were forcefully adding to the request, but since recently it stopped working, most likely because parameter integrity is now enforced in the signature.

**Comment by Hrxn** [comment]
So, youtube-dl was using `ratebypass` as well?

**Comment by Kriste00** [comment]
Any workarounds?

**Comment by Tyrrrz** [comment]
@Hrxn yes.
@Kriste00 none, except not using adaptive streams.

**Comment by Kriste00** [comment]
How to not use adaptive streams?

**Comment by Tyrrrz** [comment]
By using muxed streams

**Comment by Hrxn** [comment]
@Tyrrrz Ah, good to know.

> By using muxed streams

Well, is this really a viable alternative? Because they are limited to `1280x720`, not sure if that is really acceptable.

But, on the bright side, the download still works as expected. A bit slow maybe, but you can always queue up your desired links and let it do the work in the background.

Or am I misunderstanding something here?
> [..] most likely because parameter integrity is now enforced in the signature.

That means that the requests are still all completely correct, right?
And I hope that is also true for the returned data, i.e. the media streams. They are still intact, and the integrity is still guaranteed, or not?

**Comment by Tyrrrz** [comment]
You are correct on all accounts

**Comment by Kriste00** [comment]
Is higher videoquality = better audio quality

**Comment by SlowLogicBoy** [comment]
@Kriste00 no

**Comment by Kriste00** [comment]
I mean Mixed streams

**Comment by Tyrrrz** [comment]
Yeah, generally higher videoquality = better audio quality for muxed streams

**Comment by Tyrrrz** [comment]
From what I can tell, parameter set is now somehow enforced by signature because changing values will result in a forbidden error. That means that to get adaptive streams with rate bypass, we'd need it to already be present when requested from `get_video_info` or find a way to re-calculate signature and make it valid. Or maybe use partial streams or somethign.

**Comment by Hrxn** [comment]
@Tyrrrz Thank you for your answer, really appreciated!

**Comment by Giggitybyte** [comment]
Any news on this?

**Comment by Tyrrrz** [comment]
Well, when you open a video in browser, it plays sequential partial streams, but they are nowhere to be found in original manifest or dash manifest (which in turn is almost never available too). It makes me think that they are somehow set from the JS code.

**Comment by Tyrrrz** [comment]
One possibility that I haven't tried yet is to download the stream in multiple parts from multiple connections, not sure if that will work though.

**Comment by shikhir-arora** [comment]
I'm not using YouTubeExplode here, but that doesn't really work. It scales a bit and certainly helps with large files (but we're still talking several minutes to download an hour video, better than the hour it could take but not suitable for real-time). With `youtube-dl`: https://github.com/GieselaDev/Giesela/commit/222d41796d0318b0fd61472c7703751d0577d85e#commitcomment-27136405

**Comment by Tyrrrz** [comment]
So good news, I guess. I quickly threw together a segmented downloader and it managed to download a 3:50 video in less than a second, compared to ~2 minutes from before.

**Comment by Kriste00** [comment]
Yay

**Comment by Tyrrrz** [comment]
You can try the segmented downloader on the `segmented-download` branch with the demo projects and see how it works for you. It's still work in progress and if you have comments, please post them in #89.

**Comment by Kriste00** [comment]
Could you make a myget beta build for this.

**Comment by Giggitybyte** [comment]
I was just about to make a new issue requesting this ^ 
Automatic MyGet builds for this repo would be very helpful.

**Comment by Tyrrrz** [comment]
I could set up MyGet or just use AppVeyor's nuget feed, but usually I can publish a pre-release fast enough for this to not be necessary.
Speaking of which, latest changes are available in new alpha release, which should be indexed within 10 minutes from this post: https://www.nuget.org/packages/YoutubeExplode/4.1.0-alpha3

**Comment by Giggitybyte** [comment]
4 hours later :(

**Comment by Tyrrrz** [comment]
Well that's weird

**Comment by Tyrrrz** [comment]
At least it definitely uploaded
![2018-01-29 13_10_52-publish package](https://user-images.githubusercontent.com/1935960/35507579-e6a351a4-04f5-11e8-9adb-d48f5fe114ad.png)

**Comment by Tyrrrz** [comment]
Anyway, I investigated how the new downloader works on some videos and it was still throttling in some cases so I made some improvements to it and published `alpha4`. When nuget finally revives itself, please test it on videos of all sizes.

**Comment by Tyrrrz** [comment]
Oh, it actually got published: https://www.nuget.org/packages/YoutubeExplode/4.1.0-alpha4. Curiously, alpha3 is still returning 404 for some reason. 😆

**Comment by Giggitybyte** [comment]
I've given alpha4 a light test and it seems it downloads audio streams at full speed.
I've tried out around 15 videos with lengths varying from a few seconds to a half hour and they all seem to be downloading just as fast as the muxed streams.

I'll give some longer videos a try later, but right now everything seems to be working smoothly 👍
