### ISSUE TITLE
`GetMediaStreamAsync` To handle Youtube stuff?

### ISSUE THREAD

**Issue by SlowLogicBoy** [Tyrrrz/YoutubeExplode#99]
`GetMediaStreamAsync` that would handle rate limiting for me?

It took me 2 hours until it occured to me to check how `DownloadMediaStreamAsync` works.

I would like to get a stream that handles all the Youtube "shenanigans" for me, because right now to make my stream work I would have to basically copy `DownloadMediaStreamAsyc` code, instead of reusing it from this library?

**Comment by Tyrrrz** [comment]
I was already considering what would be the best way to do this. Will try to prioritize it.

**Comment by Tyrrrz** [comment]
Also can you clarify what's the use case for this? Are you playing the video or trying to load it into memory?

**Comment by SlowLogicBoy** [comment]
trying to load into `MemoryStream`.

**Comment by Tyrrrz** [comment]
Why would you want to do that considering videos can be large?

**Comment by Tyrrrz** [comment]
You should be able to download it to file instead and steam it from there as a response. Could also be useful for caching.

**Comment by SlowLogicBoy** [comment]
True that, I might cosider this :).

**Comment by Tyrrrz** [comment]
Yeah you will have to clean up after yourself I guess, but you really shouldn't load large binary files into RAM. I will do something to make it possible though.

**Comment by SlowLogicBoy** [comment]
That's the problem :)
I need a stream that I could load into a file or through network, without loading into ram.

**Comment by Tyrrrz** [comment]
It would be really difficult to return a single stream that will run multiple HTTP requests behind the hood and I think in most use-cases it's not worth it. However I added an overload for `DownloadMediaStreamAsync` that takes stream as an output (instead of file path), this way you can copy the contents to a stream at full speed, without allocating the video in memory. In your example, however, you would need to figure out a different way to use it, because the way it is you'll still have a memory stream anyway, but at least now you won't have to copy-paste the rate-bypass logic from YoutubeExplode.
